artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/0ba3228edf9c47c28ac39e43ed769a68/artifacts
end_time: 1751710512084
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0ba3228edf9c47c28ac39e43ed769a68
run_name: fortunate-fawn-827
run_uuid: 0ba3228edf9c47c28ac39e43ed769a68
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710511980
status: 3
tags: []
user_id: arthur-gtgn
