artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/9b029afbf13443d4afc9a67096123d16/artifacts
end_time: 1751795789675
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9b029afbf13443d4afc9a67096123d16
run_name: zealous-doe-194
run_uuid: 9b029afbf13443d4afc9a67096123d16
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795789659
status: 3
tags: []
user_id: arthur-gtgn
