artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/8408086e564f491187ee1e9c09ff58a5/artifacts
end_time: 1751795829204
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8408086e564f491187ee1e9c09ff58a5
run_name: peaceful-bat-155
run_uuid: 8408086e564f491187ee1e9c09ff58a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795829187
status: 3
tags: []
user_id: arthur-gtgn
