artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/5be7e18906c34fa6bd1ade67d3391c5e/artifacts
end_time: 1751797967000
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5be7e18906c34fa6bd1ade67d3391c5e
run_name: debonair-moth-319
run_uuid: 5be7e18906c34fa6bd1ade67d3391c5e
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797966982
status: 3
tags: []
user_id: arthur-gtgn
