artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/40ac76cc5a2c4a5f91c997f2fed1a527/artifacts
end_time: 1751710080458
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 40ac76cc5a2c4a5f91c997f2fed1a527
run_name: bustling-hen-228
run_uuid: 40ac76cc5a2c4a5f91c997f2fed1a527
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710080441
status: 3
tags: []
user_id: arthur-gtgn
