artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/1c6b728932894b12970686ec658f7ec7/artifacts
end_time: 1751796449661
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 1c6b728932894b12970686ec658f7ec7
run_name: skittish-doe-944
run_uuid: 1c6b728932894b12970686ec658f7ec7
source_name: ''
source_type: 4
source_version: ''
start_time: 1751796449552
status: 3
tags: []
user_id: arthur-gtgn
