artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/3116e4a841ae497aba6abb215be7f5b5/artifacts
end_time: 1751710299876
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3116e4a841ae497aba6abb215be7f5b5
run_name: unique-shark-119
run_uuid: 3116e4a841ae497aba6abb215be7f5b5
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710299768
status: 3
tags: []
user_id: arthur-gtgn
