artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/66665ef214d04d23be1b5ab79e70a281/artifacts
end_time: 1751795942259
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 66665ef214d04d23be1b5ab79e70a281
run_name: bustling-tern-47
run_uuid: 66665ef214d04d23be1b5ab79e70a281
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795942242
status: 3
tags: []
user_id: arthur-gtgn
