artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/a3ae656894584cae972602bbe90dbecc/artifacts
end_time: 1751795829184
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a3ae656894584cae972602bbe90dbecc
run_name: bald-horse-49
run_uuid: a3ae656894584cae972602bbe90dbecc
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795829072
status: 3
tags: []
user_id: arthur-gtgn
