artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/fd5d9a3d1eef4515a2b5601c79ef4db7/artifacts
end_time: 1751797406799
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fd5d9a3d1eef4515a2b5601c79ef4db7
run_name: ambitious-stork-220
run_uuid: fd5d9a3d1eef4515a2b5601c79ef4db7
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797406783
status: 3
tags: []
user_id: arthur-gtgn
