artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/54d110756d814309997ed591e07c93d7/artifacts
end_time: 1751710512102
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 54d110756d814309997ed591e07c93d7
run_name: carefree-kit-677
run_uuid: 54d110756d814309997ed591e07c93d7
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710512086
status: 3
tags: []
user_id: arthur-gtgn
