artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/14560d4d34f64550a43121ebd8cc9393/artifacts
end_time: 1751710157821
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 14560d4d34f64550a43121ebd8cc9393
run_name: valuable-horse-339
run_uuid: 14560d4d34f64550a43121ebd8cc9393
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710157804
status: 3
tags: []
user_id: arthur-gtgn
