artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/f95919ea09754a8791adb19ba25db424/artifacts
end_time: 1751796449680
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f95919ea09754a8791adb19ba25db424
run_name: wise-sheep-174
run_uuid: f95919ea09754a8791adb19ba25db424
source_name: ''
source_type: 4
source_version: ''
start_time: 1751796449664
status: 3
tags: []
user_id: arthur-gtgn
