artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/f74e4c42d1bd482b8cf5438be5d10bd5/artifacts
end_time: 1751797954476
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f74e4c42d1bd482b8cf5438be5d10bd5
run_name: righteous-gnu-841
run_uuid: f74e4c42d1bd482b8cf5438be5d10bd5
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797954462
status: 3
tags: []
user_id: arthur-gtgn
