artifact_location: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0
creation_time: 1751709766021
experiment_id: '0'
last_update_time: 1751709766021
lifecycle_stage: active
name: Default
