artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/65607af8678043bf988018762642c6d8/artifacts
end_time: 1751710157801
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 65607af8678043bf988018762642c6d8
run_name: adorable-gnat-336
run_uuid: 65607af8678043bf988018762642c6d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710157695
status: 3
tags: []
user_id: arthur-gtgn
