artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/db97802cbe2845359824e58e98ed5d30/artifacts
end_time: 1751710299895
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: db97802cbe2845359824e58e98ed5d30
run_name: fearless-loon-973
run_uuid: db97802cbe2845359824e58e98ed5d30
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710299878
status: 3
tags: []
user_id: arthur-gtgn
