artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/c6b17245fda94b0d96bed68867cd2d2e/artifacts
end_time: 1751797954605
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c6b17245fda94b0d96bed68867cd2d2e
run_name: enthused-swan-773
run_uuid: c6b17245fda94b0d96bed68867cd2d2e
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797954495
status: 3
tags: []
user_id: arthur-gtgn
