artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/87fdbf1cae024b6588586aaf63057259/artifacts
end_time: 1751796645006
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 87fdbf1cae024b6588586aaf63057259
run_name: redolent-ant-552
run_uuid: 87fdbf1cae024b6588586aaf63057259
source_name: ''
source_type: 4
source_version: ''
start_time: 1751796644896
status: 3
tags: []
user_id: arthur-gtgn
