artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/3e80a05205b949b081b6956297a8bbf5/artifacts
end_time: 1751797954624
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3e80a05205b949b081b6956297a8bbf5
run_name: silent-ray-980
run_uuid: 3e80a05205b949b081b6956297a8bbf5
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797954607
status: 3
tags: []
user_id: arthur-gtgn
