artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/c5698bf7d56f4b50b5821e05f69a32d8/artifacts
end_time: 1751795789656
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c5698bf7d56f4b50b5821e05f69a32d8
run_name: respected-wolf-239
run_uuid: c5698bf7d56f4b50b5821e05f69a32d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795789549
status: 3
tags: []
user_id: arthur-gtgn
