artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/2f1f6dcfa7574c33b30c2196a5de07e7/artifacts
end_time: 1751795860665
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2f1f6dcfa7574c33b30c2196a5de07e7
run_name: invincible-rat-529
run_uuid: 2f1f6dcfa7574c33b30c2196a5de07e7
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795860648
status: 3
tags: []
user_id: arthur-gtgn
