artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/132d7d9d91d1443385b69f255fce0209/artifacts
end_time: 1751710688917
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 132d7d9d91d1443385b69f255fce0209
run_name: thoughtful-bat-751
run_uuid: 132d7d9d91d1443385b69f255fce0209
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710688806
status: 3
tags: []
user_id: arthur-gtgn
