artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/92e93f36595e4464ba3c9150f5333373/artifacts
end_time: 1751795860646
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 92e93f36595e4464ba3c9150f5333373
run_name: merciful-owl-785
run_uuid: 92e93f36595e4464ba3c9150f5333373
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795860538
status: 3
tags: []
user_id: arthur-gtgn
