artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/a1ab951ee594401fa4575ef65ff10277/artifacts
end_time: 1751797966849
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a1ab951ee594401fa4575ef65ff10277
run_name: selective-yak-766
run_uuid: a1ab951ee594401fa4575ef65ff10277
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797966835
status: 3
tags: []
user_id: arthur-gtgn
