artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/6c8c5c2c0c5f49cb85a047e63269aeab/artifacts
end_time: 1751709766279
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6c8c5c2c0c5f49cb85a047e63269aeab
run_name: gregarious-cub-63
run_uuid: 6c8c5c2c0c5f49cb85a047e63269aeab
source_name: ''
source_type: 4
source_version: ''
start_time: 1751709766261
status: 3
tags: []
user_id: arthur-gtgn
