artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/2f566d4fdc7147f1829a74dec1124875/artifacts
end_time: 1751795942240
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2f566d4fdc7147f1829a74dec1124875
run_name: blushing-dove-43
run_uuid: 2f566d4fdc7147f1829a74dec1124875
source_name: ''
source_type: 4
source_version: ''
start_time: 1751795942131
status: 3
tags: []
user_id: arthur-gtgn
