artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/b35212c63fc84854bd1d15e5d2648521/artifacts
end_time: 1751797966980
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b35212c63fc84854bd1d15e5d2648521
run_name: unequaled-bee-797
run_uuid: b35212c63fc84854bd1d15e5d2648521
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797966868
status: 3
tags: []
user_id: arthur-gtgn
