artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/af5cdc3094e44281964c86c7a7b1f895/artifacts
end_time: 1751796645026
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: af5cdc3094e44281964c86c7a7b1f895
run_name: serious-ox-244
run_uuid: af5cdc3094e44281964c86c7a7b1f895
source_name: ''
source_type: 4
source_version: ''
start_time: 1751796645009
status: 3
tags: []
user_id: arthur-gtgn
