artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/894df791051049309b2dc4c402509fb5/artifacts
end_time: 1751710080438
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 894df791051049309b2dc4c402509fb5
run_name: entertaining-cow-104
run_uuid: 894df791051049309b2dc4c402509fb5
source_name: ''
source_type: 4
source_version: ''
start_time: 1751710080324
status: 3
tags: []
user_id: arthur-gtgn
