artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/6af0713afaf449dd91d1a81c32220ef4/artifacts
end_time: 1751796449214
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6af0713afaf449dd91d1a81c32220ef4
run_name: wise-kite-846
run_uuid: 6af0713afaf449dd91d1a81c32220ef4
source_name: ''
source_type: 4
source_version: ''
start_time: 1751796449200
status: 3
tags: []
user_id: arthur-gtgn
