artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/ef4aaecd56b4413996a9b7e4f3663448/artifacts
end_time: 1751709766258
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ef4aaecd56b4413996a9b7e4f3663448
run_name: auspicious-fawn-715
run_uuid: ef4aaecd56b4413996a9b7e4f3663448
source_name: ''
source_type: 4
source_version: ''
start_time: 1751709766148
status: 3
tags: []
user_id: arthur-gtgn
