artifact_uri: /Users/arthurgatignol/Developer/M1-Dev/DevOps/devops-final-project/default/0/79f15f5367984d26a9c9f223797f0401/artifacts
end_time: 1751797406780
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 79f15f5367984d26a9c9f223797f0401
run_name: suave-owl-555
run_uuid: 79f15f5367984d26a9c9f223797f0401
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797406672
status: 3
tags: []
user_id: arthur-gtgn
