name: Deploy to Staging on dev push

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  push-to-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into staging and push
        run: |
          # Switch to staging branch (create if missing)
          if git show-ref --quiet refs/heads/staging; then
            git checkout staging
          else
            git checkout -b staging
          fi
          # Merge changes from dev
          git merge dev --no-ff -m "chore: merge changes from dev to staging"
          # Push updated staging
          git push origin staging
